import type { ViewId } from '@/src/state/AppContext'

/** Dashboard navigation — plain data so server components (landing page) can import it too. */
export const NAV_ITEMS: { id: ViewId; label: string; group: string }[] = [
  { id: 'briefing', label: 'Executive Briefing', group: 'Executive' },
  { id: 'board', label: 'Board Pack', group: 'Executive' },
  { id: 'update', label: 'Investor Update', group: 'Executive' },
  { id: 'arrbridge', label: 'ARR Bridge', group: 'Executive' },
  { id: 'alerts', label: 'Alerts', group: 'Executive' },
  { id: 'issues', label: 'Data Issues', group: 'Executive' },
  { id: 'overview', label: 'Overview', group: 'Analysis' },
  { id: 'mrr', label: 'MRR', group: 'Analysis' },
  { id: 'growth', label: 'Growth', group: 'Analysis' },
  { id: 'forecast', label: 'Forecast', group: 'Analysis' },
  { id: 'goals', label: 'Goals & Pacing', group: 'Analysis' },
  { id: 'salesreps', label: 'Sales Reps', group: 'Analysis' },
  { id: 'pipeline', label: 'Pipeline', group: 'Analysis' },
  { id: 'trends', label: 'Trends', group: 'Analysis' },
  { id: 'cohorts', label: 'Cohorts', group: 'Analysis' },
  { id: 'retention', label: 'Retention Lab', group: 'Analysis' },
  { id: 'segments', label: 'Segments', group: 'Analysis' },
  { id: 'geo', label: 'Markets', group: 'Analysis' },
  { id: 'customers', label: 'Customers', group: 'Analysis' },
  { id: 'health', label: 'Customer Health', group: 'Analysis' },
  { id: 'churnwarn', label: 'Churn Warning', group: 'Analysis' },
  { id: 'expansion', label: 'Expansion Radar', group: 'Analysis' },
  { id: 'risk', label: 'Risk & Concentration', group: 'Analysis' },
  { id: 'bins', label: 'Revenue Bins', group: 'Analysis' },
  { id: 'benchmarks', label: 'Benchmarks', group: 'Analysis' },
  { id: 'unitecon', label: 'Unit Economics', group: 'Analysis' },
  { id: 'efficiency', label: 'Efficiency Lab', group: 'Analysis' },
  { id: 'product', label: 'Product & Deferred', group: 'Analysis' },
  { id: 'pricing', label: 'Price Changes', group: 'Analysis' },
  { id: 'migrations', label: 'Plan Migrations', group: 'Analysis' },
  { id: 'collections', label: 'Cash Calendar', group: 'Analysis' },
  { id: 'connectors', label: 'Workspace', group: 'Platform' },
]
